variables:
  CONTAINER_PROJECT_PATH: /miracum-etl/fhir-gateway

include:
  - project: "devops/ci-templates"
    file: "/standard/.container-build.yml"

check file tidiness:
  variables:
    IGNORE: ".git,*.min.js,*.min.css,*.drawio"

e2e:
  extends:
    - .job_defaults
  stage: test
  image:
    name: docker/compose:1.26.2
    entrypoint: [""]
  before_script:
    - export IMAGE_TAG=$CI_COMMIT_SHORT_SHA
  script:
    - docker-compose -p $CI_PROJECT_NAME-$CI_COMMIT_SHORT_SHA-e2e -f tests/e2e/docker-compose.yml build
    - docker-compose -p $CI_PROJECT_NAME-$CI_COMMIT_SHORT_SHA-e2e -f tests/e2e/docker-compose.yml run gpasinit
    - docker-compose -p $CI_PROJECT_NAME-$CI_COMMIT_SHORT_SHA-e2e -f tests/e2e/docker-compose.yml run tester
  after_script:
    - docker-compose -p $CI_PROJECT_NAME-$CI_COMMIT_SHORT_SHA-e2e -f tests/e2e/docker-compose.yml down --volumes --remove-orphans
