logging:
  level:
    org:
      miracum: debug

services:
  loinc:
    conversions:
      url: "http://localhost:19090/api/v1"
      enabled: true
      failOnError: false
  pseudonymizer:
    enabled: true
    url: "http://localhost:5000/fhir"
  fhirServer:
    url: "http://localhost:8082/fhir"
    enabled: false
  psql:
    enabled: true
  kafka:
    enabled: true

opentracing:
  jaeger:
    probabilistic-sampler:
      sampling-rate: 1
    log-spans: true

spring:
  datasource:
    url: jdbc:postgresql://localhost:15432/fhir
    username: postgres
    password: postgres
  kafka:
    bootstrapServers: localhost:9092
