management:
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    livenessstate:
      enabled: true
    readynessstate:
      enabled: true

management.endpoint.health.group.liveness.include: livenessStateProbeIndicator,refreshScope,diskSpace
management.endpoint.health.group.readiness.include: readinessStateProbeIndicator

spring:
  datasource:
    url: jdbc:postgresql://localhost:15432/fhir
    username: postgres
    password: postgres
    schema: classpath:/schema.sql
    initialization-mode: always
    hikari:
      leakDetectionThreshold: 5000  
      maxLifetime: 900000
  application:
    name: "fhir-gateway"

services:
  loinc:
    conversions:
      url: "http://loinc-converter:8080/api/v1"
      enabled: true
      failOnError: false
  pseudonymizer:
    enabled: true
    url: "http://fhir-pseudonymizer:8080/fhir"
  fhirServer:
    url: "http://fhir-server:8080/fhir"
    enabled: false
  psql:
    enabled: true

fhir:
  systems:
    loinc: "http://loinc.org"

opentracing:
  jaeger:
    udp-sender:
      host: localhost
    log-spans: false

logging:
  level:
    com.zaxxer.hikari: DEBUG
