management:
  endpoints:
    web:
      exposure:
        include: "health, prometheus"
      base-path: /
      path-mapping:
        health: health
        prometheus: metrics
  endpoint:
    health:
      show-details: always

spring:
  datasource:
    url: jdbc:postgresql://localhost:15432/fhir
    username: postgres
    password: postgres
    schema: classpath:/schema.sql
    initialization-mode: always

services:
  loinc:
    conversions:
      url: "http://localhost:8083/conversions"
      healthCheck: "http://localhost:8083/health"
  gpas:
    domains:
      patient: "DEV"
      case: "DEV"
      report: "DEV"
    api:
      url: "http://localhost:8084/gpas/gpasService?wsdl"
    enabled: true

fhir:
  systems:
    encounterId: "https://diz.uk-erlangen.de/fhir/NamingSystem/identifier/EncounterId"
    patientId: "https://diz.uk-erlangen.de/fhir/NamingSystem/identifier/PatientId"
    insuranceNumber: "http://fhir.de/CodeSystem/identifier-type-de-basis"
    reportId: "https://diz.uk-erlangen.de/fhir/NamingSystem/identifier/ReportId"
