version: "3.7"

services:
  fhir-db:
    image: postgres:12.2
    ports:
      - 15432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fhir

  loinc-converter:
    image: docker.miracum.org/miracum-etl/loinc-conversion:v1.2.0
    ports:
      - "8083:8080"
