version: "3.7"

services:
  gateway:
    image: docker.miracum.org/miracum-etl/fhir-gateway:$IMAGE_TAG
    ports:
      - 18080:8080
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL:-jdbc:postgresql://fhir-db:5432/fhir}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME:-postgres}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD:-postgres}
      SERVICES_GPAS_ENABLED: ${SERVICES_GPAS_ENABLED:-true}
      SERVICES_GPAS_API_URL: ${SERVICES_GPAS_API_URL:-http://gpas:8080/gpas/gpasService?wsdl}
      SERVICES_GPAS_DOMAINS_PATIENT: ${SERVICES_GPAS_DOMAINS_PATIENT:-PSN-REPO-PID}
      SERVICES_GPAS_DOMAINS_CASE: ${SERVICES_GPAS_DOMAINS_CASE:-PSN-REPO-CID}
      SERVICES_GPAS_DOMAINS_REPORT: ${SERVICES_GPAS_DOMAINS_REPORT:-PSN-REPO-REPID}
      SERVICES_LOINC_CONVERSIONS_URL: ${SERVICES_LOINC_CONVERSIONS_URL:-http://loinc-converter:8080/conversions}
      SERVICES_FHIRSERVER_URL: ${SERVICES_FHIRSERVER_URL:-http://fhir-server:8080/fhir}
      SERVICES_FHIRSERVER_ENABLED: ${SERVICES_FHIRSERVER_ENABLED:-false}
      SERVICES_PSQL_ENABLED: ${SERVICES_PSQL_ENABLED:-true}
    depends_on:
      - loinc-converter
      - fhir-db
      - gpas

  gateway-healthcheck:
    image: alpine:3.12
    entrypoint: /bin/sh
    tty: true
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--quiet",
          "--tries=1",
          "--spider",
          "http://gateway:8080/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    depends_on:
      - gateway

  loinc-converter:
    image: docker.miracum.org/miracum-etl/loinc-conversion:v1.8.4

  fhir-db:
    image: postgres:12.3
    ports:
      - 15432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fhir

  fhir-server:
    image: docker.miracum.org/miracum-data/hapi-fhir-jpaserver:v8.1.1
    ports:
      - 8082:8080
    environment:
      SERVER_NAME: ${SERVER_NAME:-HAPI FHIR Server}
      SERVER_ADDRESS: ${SERVER_ADDRESS:-http://localhost:8082/fhir}

  gpas:
    image: tmfev/gpas:1.9.1
    environment:
      JAVA_OPTS: -Xms512m -Xmx4G -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=256m -Djava.net.preferIPv4Stack=true -Djava.awt.headless=true
    ports:
      - 18081:8080
