version: "3.7"

services:
  fhir-db:
    image: postgres:12.3
    ports:
      - 15432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fhir

  loinc-converter:
    image: docker.miracum.org/miracum-etl/loinc-conversion:v1.8.3
    ports:
      - "8083:8080"

  gpas:
    image: tmfev/gpas:1.9.1
    environment:
      JAVA_OPTS: -Xms512m -Xmx4G -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=256m -Djava.net.preferIPv4Stack=true -Djava.awt.headless=true
    ports:
      - "8084:8080"

  gpasinit:
    image: curlimages/curl:7.70.0
    command: -X POST
      -H 'Content-Type:application/xml'
      -d '<?xml version="1.0" encoding="UTF-8"?>
            <soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:psn="http://psn.ttp.ganimed.icmvc.emau.org/">
              <soapenv:Header/>
              <soapenv:Body>
                <psn:addDomain>
                  <domainDTO>
                    <name>DEV</name>
                    <checkDigitClass>org.emau.icmvc.ganimed.ttp.psn.generator.ReedSolomonLagrange</checkDigitClass>
                    <alphabet>org.emau.icmvc.ganimed.ttp.psn.alphabets.Symbol31</alphabet>
                    <properties>PSN_LENGTH=10;PSN_PREFIX=DEV-ID.;INCLUDE_PREFIX_IN_CHECK_DIGIT_CALCULATION=false;PSNS_DELETABLE=true;MAX_DETECTED_ERRORS=2;</properties>
                    <comment>DEV Domain</comment>
                  </domainDTO>
                </psn:addDomain>
              </soapenv:Body>
            </soapenv:Envelope>'
      --retry-connrefuse
      --connect-timeout 10
      --max-time 60
      --retry 5
      --retry-delay 10
      http://gpas:8080/gpas/DomainService
    depends_on:
      - gpas
